version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  besu-net:

services:

  prometheus:
    image: prom/prometheus:v2.23.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - besu:besu
    depends_on:
      - besu
    networks:
      - besu-net
    restart: always

  grafana:
    image: grafana/grafana:7.3.6
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - besu-net
    restart: always

  pushgateway:
    image: prom/pushgateway:v1.4.0
    ports:
      - 9091:9091
    depends_on:
      - besu
    networks:
      - besu-net
    restart: always

  besu:
    image: hyperledger/besu:$VERSION
    ports:
      - 8545:8545
      - 9545:9545
    networks:
      - besu-net
    volumes:
      - $HOME/.mantis/development/besu:/var/lib/besu
    command: --rpc-http-cors-origins="all" --rpc-http-enabled --metrics-push-enabled --metrics-push-port=9091 --metrics-push-host=pushgateway --sync-mode=FULL
    restart: always
